name: Deploy

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          deploy-branch: gh-pages
          access-token: ${{ secrets.ACCESS_TOKEN }}
